function []=lunwen()
wavename=uigetfile({'*.wav'});
[s,fs,nbits]=wavread(wavename);
N=length(s);
t=(0:N-1)/fs;

%%%%%%%%%%%%%%%%%%%%%%%%原始%%%%%%%%%%%%%%%%%%%%%
figure(1)
subplot(2,1,1)
plot(t,s)
title('原始信号时域图','fontsize',25)
xlabel('时间/s','fontsize',15)
ylabel('幅度','fontsize',15)
subplot(2,1,2)
spectrogram(s,hamming(480),240)
title('原始信号语谱图','fontsize',25)
sound(s,fs)
%%%%%%%%%%%%%%%%%%%%%%%%带噪%%%%%%%%%%%%%%%%%%%%
figure(2)
snoise=s+0.1*rand(length(s),1);   
subplot(2,1,1)
plot(t,snoise)
title('带噪信号时域图','fontsize',25)
xlabel('时间/s','fontsize',15)
ylabel('幅度','fontsize',15)
subplot(2,1,2)
spectrogram(snoise,hamming(480),240)
title('带噪信号语谱图','fontsize',25)
sound(snoise,fs)
%%%%%%%%%%%%%%%%%%%%%%%%%%%谱减法%%%%%%%%%%%%%%%%%%%
figure(3)
pp.g=2;pp.e=1;pp.ne=1;
snoise_pujian=specsub(snoise,fs,pp);   
subplot(2,1,1)
plot(t,snoise_pujian)
title('谱减法增强信号时域图','fontsize',25)
xlabel('时间/s','fontsize',15)
ylabel('幅度','fontsize',15)
subplot(2,1,2)
spectrogram(snoise_pujian,hamming(480),240)
title('谱减法增强信号语谱图','fontsize',25)
sound(snoise_pujian,fs)
%%%%%%%%%%%%%%%%%%%%%%%%%%%维纳滤波%%%%%%%%%%%%%%%%%%%
figure(4)
pp.g=2;pp.e=2;pp.ne=1;
snoise_weina=specsub(snoise,fs,pp);   
subplot(2,1,1)
plot(t,snoise_weina)
title('维纳滤波法增强信号时域图','fontsize',25)
xlabel('时间/s','fontsize',15)
ylabel('幅度','fontsize',15)
subplot(2,1,2)
spectrogram(snoise_weina,hamming(480),240)
title('维纳滤波法增强信号语谱图','fontsize',25)
sound(snoise_weina,fs)
%%%%%%%%%%%%%%%%%%%%%%%%%%%MMSE谱估计%%%%%%%%%%%%%%%%%%%
figure(5)
snoise_mmse=ssubmmse(snoise,fs);   
subplot(2,1,1)
plot(t,snoise_mmse)
title('MMSE法增强信号时域图','fontsize',25)
xlabel('时间/s','fontsize',15)
ylabel('幅度','fontsize',15)
subplot(2,1,2)
spectrogram(snoise_mmse,hamming(480),240)
title('MMSE法增强信号语谱图','fontsize',25)
sound(snoise_mmse,fs)